<form class="form subscribe"
      novalidate
      action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
      method="post"
      data-mage-init='{"validation": {"errorClass": "mage-error"}}'
      id="newsletter-validate-detail-popup">
    <div class="field newsletter">
        <div class="control">
            <input name="email" type="email" id="newsletter-popup"
                   placeholder="<?= $block->escapeHtmlAttr(__('Enter your email address')) ?>"
                   data-mage-init='{"mage/trim-input":{}}'
                   data-validate="{required:true, 'validate-email':true}"/>
        </div>
    </div>
    <div class="actions">
        <button class="action subscribe primary"
                title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>"
                type="submit"
                aria-label="Subscribe">
            <span><?= $block->escapeHtml(__('Subscribe')) ?></span>
        </button>
    </div>
</form>
